### ISSUE TITLE
boost 1.70 build error

### ISSUE THREAD

**Issue by looooo** [conda-forge/boost-feedstock#72]
linux: pentantic error (works with boost 1.68)
```
[3/45] Building CXX object CMakeFiles/ocl.dir/pythonlib/ocl_algo.cpp.o
FAILED: CMakeFiles/ocl.dir/pythonlib/ocl_algo.cpp.o 
$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++  -Docl_EXPORTS -I. -I$PREFIX/include/python3.6m -I$SRC_DIR/src/cutters -I$SRC_DIR/src/geo -I$SRC_DIR/src/algo -I$SRC_DIR/src/dropcutter -I$SRC_DIR/src/common -I$SRC_DIR/src -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/opencamlib-2018.08 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -fopenmp -O3 -DNDEBUG -fPIC   -Wall -Wno-deprecated -pedantic-errors -std=gnu++11 -MD -MT CMakeFiles/ocl.dir/pythonlib/ocl_algo.cpp.o -MF CMakeFiles/ocl.dir/pythonlib/ocl_algo.cpp.o.d -o CMakeFiles/ocl.dir/pythonlib/ocl_algo.cpp.o -c $SRC_DIR/src/pythonlib/ocl_algo.cpp
In file included from $PREFIX/include/boost/python/object/function_handle.hpp:8:0,
                 from $PREFIX/include/boost/python/converter/arg_to_python.hpp:19,
                 from $PREFIX/include/boost/python/call.hpp:15,
                 from $PREFIX/include/boost/python/object_core.hpp:14,
                 from $PREFIX/include/boost/python/args.hpp:22,
                 from $PREFIX/include/boost/python.hpp:11,
                 from $SRC_DIR/src/pythonlib/ocl_algo.cpp:22:
$PREFIX/include/boost/python/detail/caller.hpp:127:2: error: extra ';' [-Wpedantic]
```

maybe this should be reported to boost directly.

**Comment by jschueller** [comment]
https://github.com/boostorg/python/pull/268
